
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: hkoo
    password: dlwngur12
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 494197804420-1ke3o3d15mt52k0n5k54ip8920ciujjp.apps.googleusercontent.com
            client-secret: sdZkIXaOdfTnBiIsP8VUdok8
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 9191
